export { PrismaExamRepository } from './prisma-exam-repository'
export { PrismaQuestionRepository } from './prisma-question-repository'
export { PrismaSimulationRepository } from './prisma-simulation-repository'
export { PrismaAlternativeRepository } from './prisma-alternative-repository'
export { PrismaExamRecordRepository } from './prisma-exam-record-repository'
